var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc(-1,false);
subject.inc(-1,undefined);
subject.inc(1,'');
subject.inc(-1,undefined);
subject.inc(-1,'');
subject.inc(1,'');
subject.weird(2,1,410,"nksnlfv");
subject.weird(0,1,410,"raju");
subject.weird(0,3,412,'');
subject.weird(0,1,410,'rand');
subject.weird(0,1,410,"lkkkk");
subject.weird(0,3,412,"nksnlfv");
mock({"path/fileExists":{"rand":""},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"rand":""},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"rand":""},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"rand":""},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"rand":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.normalize('');
subject.normalize('');
subject.normalize('');
subject.normalize('');
subject.normalize('');
subject.normalize('');
subject.format('2126457146','','do it');
subject.format('','',false);
subject.format('','','');
subject.format('','','');
subject.format('','','');
subject.format('','','');
subject.blackListNumber("412"+"111222");
subject.blackListNumber('abcdefghi');
subject.blackListNumber('123456789');
subject.blackListNumber('thisispho');
subject.blackListNumber('');
subject.blackListNumber('');
